---
title: "Volume"
author: "Tobi & Lukas"
date: "Rendered `r format(Sys.time(), '%F %H:%M')`"
output:
  html_document
---

```{r setup_volume, include=FALSE}
source("setup.R")
```

## By State
 
```{r volume_state}
penis %>% 
  gather(key = state, value = volume, volume_flaccid, volume_erect) %>%
  mutate(state = factor(state, 
                        levels = c("volume_flaccid", "volume_erect"), 
                        labels =  c("Flaccid", "Erect"))) %>%
  {
    ggplot(., aes(x = volume, fill = state, color = state)) +
    geom_histogram(binwidth = 5, alpha = .7, position = "dodge") +
    scale_x_continuous(breaks = seq(0, 500, 25), 
                       minor_breaks = seq(0, 500, 5),
                       labels = math_format(.x ~cm^3),
                       sec.axis = sec_axis(trans = ~./2.54^3, 
                                           labels = math_format(.x ~inch^3))) +
    scale_fill_brewer(palette = "Paired") +
    scale_color_brewer(palette = "Paired") +
    labs(title = "World Penis Data", subtitle = "Volume by State",
         x = "Volume", y = "Frequency", 
         fill = "State", color = "State", caption = plot_caption) +
    theme(legend.position = "top")
  }
```

### By State and Region

```{r volume_state_region}
penis %>% 
  gather(key = state, value = volume, volume_flaccid, volume_erect) %>%
  mutate(state = factor(state, 
                        levels = c("volume_flaccid", "volume_erect"), 
                        labels =  c("Flaccid", "Erect"))) %>%
  group_by(Region) %>%
  mutate(order_volume = mean(volume)) %>%
  {
    ggplot(., aes(x = reorder(Region, order_volume), y = volume, 
                  fill = state, color = state)) +
    geom_boxplot(alpha = .7) +
    coord_flip() +
    scale_y_continuous(breaks = seq(0, 500, 25), 
                       minor_breaks = seq(0, 500, 5),
                       labels = math_format(.x ~cm^3),
                       sec.axis = sec_axis(trans = ~./2.54^3, 
                                           labels = math_format(.x ~inch^3))) +
    scale_fill_brewer(palette = "Paired") +
    scale_color_brewer(palette = "Paired") +
    labs(title = "World Penis Data", subtitle = "Volume by State",
         x = "", y = "Volume", 
         fill = "State", color = "State", caption = plot_caption) +
    theme(axis.text.y = element_text(size = rel(1.2)),
          legend.position = "top")
  }

# CIs
penis_long %>%
  group_by(Region) %>%
  mutate(order_volume = mean(volume)) %>%
  {
    ggplot(., aes(x = reorder(Region, order_volume), y = volume,
                  fill = state, color = state)) +
    stat_summary(fun.data = mean_cl_normal, geom = "errorbar") +
    stat_summary(fun.y = mean, geom = "point", size = 2) +
    coord_flip() +
    scale_y_continuous(breaks = seq(0, 500, 25),
                       minor_breaks = seq(0, 500, 5),
                       labels = math_format(.x ~cm^3),
                       sec.axis = sec_axis(trans = ~./2.54^3, 
                                           labels = math_format(.x ~inch^3))) +
    scale_color_brewer(palette = "Paired") +
    labs(title = "World Penis Data", subtitle = "Volume by State",
         x = "", y = "Volume",
         fill = "State", color = "State", caption = plot_caption) +
    theme(axis.text.y = element_text(size = rel(1.2)),
          legend.position = "top")
  }
```


## Choropleth-Penismap <small>because why not?</small>

A choropleth map displaying the worldwide distribution of the volume of erect penisses. Enjoy.

```{r choropenis_vol_erect}
data(worldgeojson, package = "highcharter")

idk <- data.frame(q = c(0, exp(1:2)/exp(2)),
                  c = rev(substring(viridis(2+1, option = "D"), 0, 7))) %>% 
  list_parse2()

highchart() %>% 
  hc_add_series_map(worldgeojson, map, value = "volume_erect", joinBy = "iso3",
                    name = "Penis Volume (erect)") %>% 
  hc_title(text = "Erect Penis Volume by Country") %>% 
  hc_tooltip(valueDecimals = 2, valuePrefix = "<b>", valueSuffix = " cm<sup>2</sup></b>", 
             useHTML = TRUE) %>% 
  hc_colorAxis(stops = idk, min = 80, max = 260) %>% 
  hc_legend(enabled = TRUE) %>% 
  hc_mapNavigation(enabled = TRUE)
```

